### python 內建資料結構： list/dict/set
- 取得每個值，必須使用 for...in...

In [4]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]
# 將同一列的數字相加
len(student1)  #長度
for i in range(len(student1)):       #list/dict 若要一個一個取出裡面的值，一定是配合 for...in...
    scores = student1[i] + student2[i]
    print(scores)
    print(i)
    print("==============")

144
0
170
1
164
2
167
3
177
4


In [5]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

student1 + student2   #(串接list)

[69, 78, 72, 91, 85, 75, 92, 92, 76, 92]

### python 擴充的資料結構
- numpy
- Series
- DataFrame
可以陣列運算


### numpy 陣列運算
numpy.array
- numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
Create an array (list).

In [1]:
import numpy as np
from numpy import ndarray
student1:ndarray = np.array([69, 78, 72, 91, 85])
student2:ndarray = np.array([75, 92, 92, 76, 92])
print(type(student1))
print(student1 + student2)
#可以做陣列運算,不需使用for...in

totols:ndarray= student1 + student2
for total in totols:
    print("=========")
    print(total)


<class 'numpy.ndarray'>
[144 170 164 167 177]
144
170
164
167
177


In [4]:
# 二維資料轉換 list內有list
array:ndarray = np.array([[1,2,3],[4,5,6]])
print(array)
#property 查詢
#ndim,shape,size,dtype

print(array.ndim)   #(維度)
print(array.shape)  #(形狀)：第一維(最外面括號)2個；第二維(第二層括號)3個
print(array.size)   #(元素數量)
print(array.dtype)  #(資料類型)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int32


In [14]:
# 亂數  (最小值,最大值,size=(第一層括號元素,第二層括號元素)
np.random.randint(50,101,size=(10, 5))

array([[96, 59, 84, 80, 79],
       [59, 83, 61, 87, 84],
       [73, 91, 88, 73, 77],
       [93, 94, 92, 58, 91],
       [50, 72, 70, 58, 70],
       [51, 98, 50, 62, 81],
       [82, 53, 64, 84, 78],
       [76, 59, 57, 62, 98],
       [87, 56, 92, 84, 83],
       [63, 68, 82, 82, 77]])